// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
typedef SWIFT_ENUM(NSInteger, AuthType) {
  AuthTypeDefault = 0,
  AuthTypePreview = 1,
  AuthTypeDownload = 2,
  AuthTypeUpload = 3,
};

enum LogLevel : NSInteger;

SWIFT_CLASS("_TtC13YunkuSwiftSDK6Config")
@interface Config : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL logPrint;)
+ (BOOL)logPrint SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogPrint:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum LogLevel logLevel;)
+ (enum LogLevel)logLevel SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogLevel:(enum LogLevel)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13YunkuSwiftSDK11SignAbility")
@interface SignAbility : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum NetType : NSInteger;
@protocol UploadCallBack;
@class UploadManager;

SWIFT_CLASS("_TtC13YunkuSwiftSDK14EntFileManager")
@interface EntFileManager : SignAbility
- (nonnull instancetype)initWithOrgClientId:(NSString * _Nonnull)orgClientId orgClientSecret:(NSString * _Nonnull)orgClientSecret OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)getFileList:(NSInteger)start fullPath:(NSString * _Nonnull)fullPath SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getUpdateList:(BOOL)isCompare fetchDateline:(NSInteger)fetchDateline SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getFileInfo:(NSString * _Nonnull)fullPath type:(enum NetType)type SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)createFolder:(NSString * _Nonnull)fullPath opName:(NSString * _Nonnull)opName SWIFT_WARN_UNUSED_RESULT;
- (UploadManager * _Nonnull)uploadByBlock:(NSString * _Nonnull)localPath fullPath:(NSString * _Nonnull)fullPath opName:(NSString * _Nonnull)opName opId:(NSInteger)opId overwrite:(BOOL)overwrite delegate:(id <UploadCallBack> _Nonnull)delegate SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)createFile:(NSString * _Nonnull)fullPath opName:(NSString * _Nonnull)opName data:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)del:(NSString * _Nonnull)fullPaths opName:(NSString * _Nonnull)opName SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)move:(NSString * _Nonnull)fullPath destFullPath:(NSString * _Nonnull)destFullPath opName:(NSString * _Nonnull)opName SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)link:(NSString * _Nonnull)fullPath deadline:(NSInteger)deadline authType:(enum AuthType)authType password:(NSString * _Nullable)password SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)sendmsg:(NSString * _Nonnull)title text:(NSString * _Nonnull)text image:(NSString * _Nullable)image linkUrl:(NSString * _Nullable)linkUrl opName:(NSString * _Nonnull)opName SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)links:(BOOL)fileOnly SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getUpdateCounts:(NSInteger)beginDateline endDateline:(NSInteger)endDateline showDelete:(BOOL)showDelete SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)createFileByUrl:(NSString * _Nonnull)fullPath opId:(NSInteger)opId opName:(NSString * _Null_unspecified)opName overwrite:(BOOL)overwrite fileUrl:(NSString * _Nonnull)fileUrl SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getUploadServers SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getServerSite:(NSString * _Nonnull)type SWIFT_WARN_UNUSED_RESULT;
- (EntFileManager * _Nonnull)clone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC13YunkuSwiftSDK12ParentEngine")
@interface ParentEngine : SignAbility
- (NSDictionary<NSString *, id> * _Nonnull)accessToken:(NSString * _Nonnull)username password:(NSString * _Nonnull)password SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

enum MemberType : NSInteger;

SWIFT_CLASS("_TtC13YunkuSwiftSDK13EntLibManager")
@interface EntLibManager : ParentEngine
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret isEnt:(BOOL)isEnt OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret isEnt:(BOOL)isEnt token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)create:(NSString * _Nonnull)orgName orgCapacity:(NSString * _Nullable)orgCapacity storagePointName:(NSString * _Nullable)storagePointName orgDesc:(NSString * _Nullable)orgDesc orgLogo:(NSString * _Nullable)orgLogo SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getLibList SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)bindLib:(NSInteger)orgId title:(NSString * _Nullable)title linkUrl:(NSString * _Nullable)linkUrl SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)unbindLib:(NSString * _Nonnull)orgClientId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getMembers:(NSInteger)start size:(NSInteger)size orgId:(NSInteger)orgId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)addMembers:(NSInteger)orgId roleId:(NSInteger)roleId memberIds:(NSArray<NSString *> * _Nonnull)memberIds SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)setMemberRole:(NSInteger)orgId roleId:(NSInteger)roleId memberIds:(NSArray<NSString *> * _Nonnull)memberIds SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)delMember:(NSInteger)orgId memberIds:(NSArray<NSString *> * _Nonnull)memberIds SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getGroups:(NSInteger)orgId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)addGroup:(NSInteger)orgId groupId:(NSInteger)groupId roleId:(NSInteger)roleId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)delGroup:(NSInteger)orgId groupId:(NSInteger)groupId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)setGroupRole:(NSInteger)orgId groupId:(NSInteger)groupId roleId:(NSInteger)roleId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)destroy:(NSString * _Nonnull)orgClientId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)set:(NSInteger)orgId orgName:(NSString * _Nullable)orgName orgCapacity:(NSString * _Nullable)orgCapacity orgDes:(NSString * _Nullable)orgDes orgLogo:(NSString * _Nullable)orgLogo SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getMember:(NSInteger)orgId type:(enum MemberType)type ids:(NSArray<NSString *> * _Nonnull)ids SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getInfo:(NSInteger)orgId SWIFT_WARN_UNUSED_RESULT;
- (EntLibManager * _Nonnull)clone SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13YunkuSwiftSDK10EntManager")
@interface EntManager : ParentEngine
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret isEnt:(BOOL)isEnt OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret isEnt:(BOOL)isEnt token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)getRoles SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getMembers:(NSInteger)start size:(NSInteger)size SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getGroups SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getMemberFileLink:(NSInteger)memberId fileOnly:(BOOL)fileOnly SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getMemberById:(NSInteger)memberId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getMemberByOutId:(NSString * _Nonnull)outId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getMemberByAccount:(NSString * _Nonnull)account SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)addSyncMember:(NSString * _Nonnull)oudId memberName:(NSString * _Nonnull)memberName account:(NSString * _Nonnull)account memberEmail:(NSString * _Nullable)memberEmail memberPhone:(NSString * _Nullable)memberPhone password:(NSString * _Nullable)password SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)delSyncMember:(NSArray<NSString *> * _Nonnull)members SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)addSyncGroup:(NSString * _Nonnull)outId name:(NSString * _Nonnull)name parentOutId:(NSString * _Nullable)parentOutId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)delSyncGroup:(NSArray<NSString *> * _Nonnull)groups SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)addSyncGroupMember:(NSString * _Nonnull)groupOutId members:(NSArray<NSString *> * _Nonnull)members SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)delSyncGroupMember:(NSString * _Nonnull)groupOutId members:(NSArray<NSString *> * _Nonnull)members SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)getGroupMembers:(NSInteger)groupId start:(NSInteger)start size:(NSInteger)size showChild:(BOOL)showChild SWIFT_WARN_UNUSED_RESULT;
- (EntManager * _Nonnull)clone SWIFT_WARN_UNUSED_RESULT;
@end

/// HTTP status codes as per http://en.wikipedia.org/wiki/List_of_HTTP_status_codes
/// The RF2616 standard is completely covered (http://www.ietf.org/rfc/rfc2616.txt)
typedef SWIFT_ENUM(NSInteger, HTTPStatusCode) {
  HTTPStatusCodeContinue = 100,
  HTTPStatusCodeSwitchingProtocols = 101,
  HTTPStatusCodeProcessing = 102,
  HTTPStatusCodeOk = 200,
  HTTPStatusCodeCreated = 201,
  HTTPStatusCodeAccepted = 202,
  HTTPStatusCodeNonAuthoritativeInformation = 203,
  HTTPStatusCodeNoContent = 204,
  HTTPStatusCodeResetContent = 205,
  HTTPStatusCodePartialContent = 206,
  HTTPStatusCodeMultiStatus = 207,
  HTTPStatusCodeAlreadyReported = 208,
  HTTPStatusCodeImUsed = 226,
  HTTPStatusCodeMultipleChoices = 300,
  HTTPStatusCodeMovedPermanently = 301,
  HTTPStatusCodeFound = 302,
  HTTPStatusCodeSeeOther = 303,
  HTTPStatusCodeNotModified = 304,
  HTTPStatusCodeUseProxy = 305,
  HTTPStatusCodeSwitchProxy = 306,
  HTTPStatusCodeTemporaryRedirect = 307,
  HTTPStatusCodePermanentRedirect = 308,
  HTTPStatusCodeBadRequest = 400,
  HTTPStatusCodeUnauthorized = 401,
  HTTPStatusCodePaymentRequired = 402,
  HTTPStatusCodeForbidden = 403,
  HTTPStatusCodeNotFound = 404,
  HTTPStatusCodeMethodNotAllowed = 405,
  HTTPStatusCodeNotAcceptable = 406,
  HTTPStatusCodeProxyAuthenticationRequired = 407,
  HTTPStatusCodeRequestTimeout = 408,
  HTTPStatusCodeConflict = 409,
  HTTPStatusCodeGone = 410,
  HTTPStatusCodeLengthRequired = 411,
  HTTPStatusCodePreconditionFailed = 412,
  HTTPStatusCodeRequestEntityTooLarge = 413,
  HTTPStatusCodeRequestURITooLong = 414,
  HTTPStatusCodeUnsupportedMediaType = 415,
  HTTPStatusCodeRequestedRangeNotSatisfiable = 416,
  HTTPStatusCodeExpectationFailed = 417,
  HTTPStatusCodeImATeapot = 418,
  HTTPStatusCodeAuthenticationTimeout = 419,
  HTTPStatusCodeUnprocessableEntity = 422,
  HTTPStatusCodeLocked = 423,
  HTTPStatusCodeFailedDependency = 424,
  HTTPStatusCodeUpgradeRequired = 426,
  HTTPStatusCodePreconditionRequired = 428,
  HTTPStatusCodeTooManyRequests = 429,
  HTTPStatusCodeRequestHeaderFieldsTooLarge = 431,
  HTTPStatusCodeLoginTimeout = 440,
  HTTPStatusCodeNoResponse = 444,
  HTTPStatusCodeRetryWith = 449,
  HTTPStatusCodeUnavailableForLegalReasons = 451,
  HTTPStatusCodeRequestHeaderTooLarge = 494,
  HTTPStatusCodeCertError = 495,
  HTTPStatusCodeNoCert = 496,
  HTTPStatusCodeHttpToHTTPS = 497,
  HTTPStatusCodeTokenExpired = 498,
  HTTPStatusCodeClientClosedRequest = 499,
  HTTPStatusCodeInternalServerError = 500,
  HTTPStatusCodeNotImplemented = 501,
  HTTPStatusCodeBadGateway = 502,
  HTTPStatusCodeServiceUnavailable = 503,
  HTTPStatusCodeGatewayTimeout = 504,
  HTTPStatusCodeHttpVersionNotSupported = 505,
  HTTPStatusCodeVariantAlsoNegotiates = 506,
  HTTPStatusCodeInsufficientStorage = 507,
  HTTPStatusCodeLoopDetected = 508,
  HTTPStatusCodeBandwidthLimitExceeded = 509,
  HTTPStatusCodeNotExtended = 510,
  HTTPStatusCodeNetworkAuthenticationRequired = 511,
  HTTPStatusCodeNetworkTimeoutError = 599,
};

typedef SWIFT_ENUM(NSInteger, LogLevel) {
  LogLevelInfo = 0,
  LogLevelWarning = 1,
  LogLevelError = 2,
};

typedef SWIFT_ENUM(NSInteger, MemberType) {
  MemberTypeAccount = 0,
  MemberTypeOutId = 1,
  MemberTypeMemberId = 2,
};

typedef SWIFT_ENUM(NSInteger, NetError) {
  NetErrorUnknowError = 10000,
  NetErrorSdkInnerError = 10001,
};

typedef SWIFT_ENUM(NSInteger, NetType) {
  NetTypeDefault = 0,
  NetTypeIn = 1,
};



SWIFT_CLASS("_TtC13YunkuSwiftSDK12ReturnResult")
@interface ReturnResult : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Null_unspecified result;
@property (nonatomic) NSInteger code;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (ReturnResult * _Nonnull)create:(NSDictionary<NSString *, id> * _Nonnull)dic SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_PROTOCOL("_TtP13YunkuSwiftSDK14UploadCallBack_")
@protocol UploadCallBack
- (void)onSuccess:(NSString * _Nonnull)fileHash fullPath:(NSString * _Nonnull)fullPath localPath:(NSString * _Nonnull)localPath;
- (void)onFail:(NSString * _Nullable)errorMsg errorCode:(NSInteger)errorCode fullPath:(NSString * _Nonnull)fullPath localPath:(NSString * _Nonnull)localPath;
- (void)onProgress:(float)percent fullPath:(NSString * _Nonnull)fullPath;
@end


SWIFT_CLASS("_TtC13YunkuSwiftSDK13UploadManager")
@interface UploadManager : SignAbility
- (void)stop;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

#pragma clang diagnostic pop
